const Images = {
  image1: "/assets/Images/gabriel-alenius-USXfF_ONUGo-unsplash.jpg",
  image2: "/assets/Images/billy-pasco-F5oj6SYoarc-unsplash.jpg",
  image3: "/assets/Images/geranimo-f0oe9P9Yixs-unsplash.jpg",
  image4: "/assets/Images/trail-5yOnGsKUNGw-unsplash.jpg",
  image5: "/assets/Images/alec-douglas-2Kexn4xZm1Q-unsplash.jpg",
  imageD1: "/assets/Images/destination_1_1.jpg",
  imageD2: "/assets/Images/destination_1_2.jpg",
  imageD3: "/assets/Images/destination_1_3.jpg",
  imageD4: "/assets/Images/destination_1_4.jpg",
  imageD5: "/assets/Images/destination_1_5.jpg",
  imageC5: "/assets/Images/alec-douglas-2Kexn4xZm1Q-unsplash.jpg",
  imageC2: "/assets/Images/billy-pasco-F5oj6SYoarc-unsplash.jpg",
  imageC1: "/assets/Images/gabriel-alenius-USXfF_ONUGo-unsplash.jpg",
  imageC3: "/assets/Images/geranimo-f0oe9P9Yixs-unsplash.jpg",
  imageC4: "/assets/Images/trail-5yOnGsKUNGw-unsplash.jpg",
  arrow: "/assets/Images/arrow-right3.svg",
  map: "/assets/Images/map3.svg",
  guide: "/assets/Images/guide.svg",
  gallery1: "/assets/Images/gallery_1_1.jpg",
  gallery2: "/assets/Images/gallery_1_2.jpg",
  gallery3: "/assets/Images/gallery_1_3.jpg",
  gallery4: "/assets/Images/gallery_1_4.jpg",
  gallery5: "/assets/Images/gallery_1_5.jpg",
  gallery6: "/assets/Images/gallery_1_6.jpg",
  gallery7: "/assets/Images/gallery_1_7.jpg",
  team1: "/assets/Images/team_1_1.jpg",
  team2: "/assets/Images/team_1_2.jpg",
  team3: "/assets/Images/team_1_3.jpg",
  team4: "/assets/Images/team_1_4.jpg",
  team5: "/assets/Images/team_1_5.jpg",
  brand1: "/assets/Images/brand_1_1.svg",
  brand2: "/assets/Images/brand_1_2.svg",
  brand3: "/assets/Images/brand_1_4.svg",
  worldLogo: "/assets/Images/logo3.svg",
  worldLogo2: "/assets/Images/logo4.svg",
};

export default Images;
